const mongoose = require("mongoose");

const userSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    email: { type: String, required: true, unique: true },
    password: { type: String, required: true },
    role: { type: String, enum: ["candidate", "employer", "admin"], default: "candidate" },
    resetToken: { type: String },
    resetTokenExpiry: { type: Date },
    // Profile fields for completion calculation
    profilePicture: { type: String },
    resumeUrl: { type: String }, // URL of uploaded resume
    resumeFileName: { type: String, default: "" },
    resumeFileSize: { type: Number, default: 0 },
    resumeUploadedAt: { type: Date },
    skills: [{ type: String }],
    bio: { type: String },
    phone: { type: String },
    location: { type: String },
    professionalTitle: { type: String, default: "" },
    linkedinUrl: { type: String, default: "" },
    githubUrl: { type: String, default: "" },
    portfolioUrl: { type: String, default: "" },
    experience: { type: String, default: "" },
    education: { type: String, default: "" },
    college: { type: String, default: "" },
    department: { type: String, default: "" },
    graduationYear: { type: Number },
    profileVisibility: {
      type: String,
      enum: ["public", "recruiters", "private"],
      default: "recruiters",
    },
    // Employer specific fields
    industry: { type: String, default: "" },
    companySize: { type: String, default: "" },
    foundedYear: { type: Number },
    headquarters: { type: String, default: "" },
    website: { type: String, default: "" },
    twitterUrl: { type: String, default: "" },
    facebookUrl: { type: String, default: "" },
    companyGallery: [{ type: String }],
    companyBanner: { type: String, default: "" },
    recruiterName: { type: String, default: "" },
    recruiterPosition: { type: String, default: "" },
    recruiterEmail: { type: String, default: "" },
    recruiterPhone: { type: String, default: "" },
    preferredWorkMode: { type: String, default: "" },
    preferredExperience: { type: String, default: "" },
    hiringLocations: [{ type: String }],
    companyBenefits: [{ type: String }],
    verifiedEmployer: { type: Boolean, default: false },
    profileViews: { type: Number, default: 0 },
    tagline: { type: String, default: "" },
    companyEmail: { type: String, default: "" },
    workingHours: { type: String, default: "" },
    companyMission: { type: String, default: "" },
    companyVision: { type: String, default: "" },
    companyCoreValues: { type: String, default: "" },
    companyEnvironment: { type: String, default: "" },
    officeLocations: [{
      city: { type: String, default: "" },
      state: { type: String, default: "" },
      country: { type: String, default: "" },
      mapsLink: { type: String, default: "" }
    }],
    instagramUrl: { type: String, default: "" },
    jobsPostedThisMonth: { type: Number, default: 0 },
    responseRate: { type: String, default: "94%" },
    averageHiringTime: { type: String, default: "12 Days" },
    notifications: {
      newApplications: { type: Boolean, default: true },
      interviewResponses: { type: Boolean, default: true },
      candidateMessages: { type: Boolean, default: true },
      jobExpiringSoon: { type: Boolean, default: true },
      weeklyHiringReport: { type: Boolean, default: true },
      marketingEmails: { type: Boolean, default: false },
    },
    privacy: {
      profileVisibility: { type: String, default: "public" },
      showRecruiterContact: { type: Boolean, default: true },
      allowPublicPage: { type: Boolean, default: true },
      showCompanyWebsite: { type: Boolean, default: true },
      allowSearchIndexing: { type: Boolean, default: true },
    },
    hiringPreferences: {
      defaultJobType: { type: String, default: "Full-time" },
      defaultWorkMode: { type: String, default: "On-site" },
      defaultHiringLocation: { type: String, default: "" },
      defaultSalaryCurrency: { type: String, default: "USD" },
      autoArchiveAfterDeadline: { type: Boolean, default: true },
      autoCloseFilled: { type: Boolean, default: true },
      requireResume: { type: Boolean, default: true },
      requireCoverLetter: { type: Boolean, default: false },
      enableQuickApply: { type: Boolean, default: true },
    },
    appearance: {
      theme: { type: String, default: "light" },
      accentColor: { type: String, default: "#659287" },
    },
    integrations: {
      googleCalendar: { type: Boolean, default: false },
      outlookCalendar: { type: Boolean, default: false },
      zoom: { type: Boolean, default: false },
      teams: { type: Boolean, default: false },
    },
    jwtVersion: { type: Number, default: 0 },
    lastUpdated: { type: Date, default: Date.now },
  },
  { timestamps: true }
);

module.exports = mongoose.model("User", userSchema);